// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountOperationResultsByAction(ctx context.Context, arg CountOperationResultsByActionParams) (int64, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	CreateOperationLog(ctx context.Context, arg CreateOperationLogParams) (OperationLog, error)
	CreateOperationResult(ctx context.Context, arg CreateOperationResultParams) (OperationResult, error)
	CreateTagStandard(ctx context.Context, arg CreateTagStandardParams) (TagStandard, error)
	DeleteOperation(ctx context.Context, id int64) error
	DeleteOperationLogs(ctx context.Context, operationID int64) error
	DeleteOperationResults(ctx context.Context, operationID int64) error
	DeleteTagStandard(ctx context.Context, id int64) error
	GetOperation(ctx context.Context, id int64) (Operation, error)
	GetOperationLogs(ctx context.Context, operationID int64) ([]OperationLog, error)
	GetOperationLogsByLevel(ctx context.Context, arg GetOperationLogsByLevelParams) ([]OperationLog, error)
	GetOperationResults(ctx context.Context, operationID int64) ([]OperationResult, error)
	GetOperationResultsByAction(ctx context.Context, arg GetOperationResultsByActionParams) ([]OperationResult, error)
	GetTagStandard(ctx context.Context, id int64) (TagStandard, error)
	GetTagStandardByName(ctx context.Context, name string) (TagStandard, error)
	ListOperations(ctx context.Context, arg ListOperationsParams) ([]Operation, error)
	ListOperationsByType(ctx context.Context, arg ListOperationsByTypeParams) ([]Operation, error)
	ListTagStandards(ctx context.Context) ([]TagStandard, error)
	ListTagStandardsByProvider(ctx context.Context, cloudProvider string) ([]TagStandard, error)
	UpdateOperationCompleted(ctx context.Context, arg UpdateOperationCompletedParams) (Operation, error)
	UpdateOperationStarted(ctx context.Context, arg UpdateOperationStartedParams) (Operation, error)
	UpdateOperationStatus(ctx context.Context, arg UpdateOperationStatusParams) (Operation, error)
	UpdateTagStandard(ctx context.Context, arg UpdateTagStandardParams) (TagStandard, error)
}

var _ Querier = (*Queries)(nil)
